name: pawapay_flutter
description: "Pawapay Flutter SDK"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.4.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.7.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  get_it: ^7.7.0
  json_annotation: ^4.8.1
  pretty_dio_logger: ^1.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.0.0
flutter:

